"""Rule-based report generation for Tourism REIT Asset Evaluator.

Reports generated by this module are deterministic portfolio-demo outputs. They
do not use external LLM APIs and must not be read as investment advice, credit
ratings, valuation opinions, or official regulatory conclusions.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.gatekeeper import run_gatekeeper_checks
from src.data_loader import load_financial_metrics
from src.reliability_validity import run_model_validity_pipeline
from src.scenario_simulator import simulate_asset_scenario
from src.scoring_model import load_scoring_data, run_scoring_pipeline


RISK_COLUMNS = {
    "seasonality_risk": "seasonality risk",
    "market_competition_risk": "market competition risk",
    "policy_risk": "policy risk",
    "climate_physical_risk": "climate physical risk",
    "financial_pressure_risk": "financial pressure risk",
    "platform_dependency_risk": "platform dependency risk",
}


FIELD_SOURCE_DISCLOSURE = (
    "Selected core financial fields in this report are sourced from public financial data "
    "and standardized to RMB million. Some indicators are model-derived. NOI, AFFO, "
    "estimated distribution, and maintenance CAPEX may remain model-estimated or "
    "demo-derived and should not be interpreted as official disclosed figures."
)


def _resolve_data_dir(data_dir: str | Path) -> Path:
    path = Path(data_dir)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    return path


def _latest_rows_by_asset(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty or "year" not in df.columns:
        return df.copy()
    latest_df = df.copy()
    latest_df["year"] = pd.to_numeric(latest_df["year"], errors="coerce")
    latest_df = latest_df.dropna(subset=["asset_id", "year"])
    latest_df = latest_df.sort_values(["asset_id", "year"])
    return latest_df.groupby("asset_id", as_index=False).tail(1)


def _to_float(value: Any) -> float | None:
    if value is None or pd.isna(value):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def format_number(value: Any, unit: str = "", decimals: int = 2) -> str:
    """Format numeric values and show missing values clearly."""
    numeric_value = _to_float(value)
    if numeric_value is None:
        return "Data unavailable"
    formatted = f"{numeric_value:,.{decimals}f}"
    return f"{formatted}{unit}" if unit else formatted


def format_percentage(value: Any, decimals: int = 1) -> str:
    """Format a decimal ratio such as 0.25 as 25.0%."""
    numeric_value = _to_float(value)
    if numeric_value is None:
        return "Data unavailable"
    return f"{numeric_value * 100:.{decimals}f}%"


def _format_list(values: list[str]) -> str:
    return ", ".join(values) if values else "None identified"


def _safe_value(row: pd.Series | None, column: str) -> Any:
    if row is None or column not in row:
        return None
    value = row.get(column)
    return None if pd.isna(value) else value


def get_asset_context(
    asset_id: str,
    data_dir: str | Path = "data",
    financial_data_source: str = "demo",
) -> dict[str, Any]:
    """Load asset basic info and latest available metric rows."""
    base_dir = _resolve_data_dir(data_dir)
    assets_df = pd.read_csv(base_dir / "assets.csv")
    financial_df = _latest_rows_by_asset(load_financial_metrics(financial_data_source))
    operation_df = _latest_rows_by_asset(pd.read_csv(base_dir / "operation_metrics.csv"))
    service_df = _latest_rows_by_asset(pd.read_csv(base_dir / "service_quality_metrics.csv"))
    risk_df = _latest_rows_by_asset(pd.read_csv(base_dir / "risk_metrics.csv"))
    digital_df = _latest_rows_by_asset(pd.read_csv(base_dir / "digital_maturity_metrics.csv"))

    asset_rows = assets_df[assets_df["asset_id"] == asset_id]
    if asset_rows.empty:
        raise ValueError(f"Unknown asset_id: {asset_id}")

    def first_or_none(df: pd.DataFrame) -> pd.Series | None:
        rows = df[df["asset_id"] == asset_id]
        return None if rows.empty else rows.iloc[0]

    return {
        "asset": asset_rows.iloc[0],
        "financial": first_or_none(financial_df),
        "operation": first_or_none(operation_df),
        "service_quality": first_or_none(service_df),
        "risk": first_or_none(risk_df),
        "digital_maturity": first_or_none(digital_df),
        "risk_sample": risk_df,
    }


def summarize_gatekeeper(
    asset_id: str,
    data_dir: str | Path = "data",
    financial_data_source: str = "demo",
) -> dict[str, Any]:
    """Summarize Regulatory Gatekeeper results."""
    results_df, overall_status, summary_text = run_gatekeeper_checks(
        asset_id,
        data_dir,
        financial_data_source,
    )
    return {
        "overall_status": overall_status,
        "passed_conditions": results_df.loc[results_df["status"] == "Pass", "condition"].tolist(),
        "failed_conditions": results_df.loc[results_df["status"] == "Fail", "condition"].tolist(),
        "warning_conditions": results_df.loc[results_df["status"] == "Warning", "condition"].tolist(),
        "summary_text": summary_text,
        "results_df": results_df,
    }


def summarize_score(
    asset_id: str,
    data_dir: str | Path = "data",
    weight_mode: str = "default_expert_weight",
    financial_data_source: str = "demo",
) -> dict[str, Any]:
    """Summarize REITs suitability score for one asset."""
    _indicator_scores_df, module_scores_df, total_scores_df = run_scoring_pipeline(
        data_dir,
        weight_mode,
        financial_data_source,
    )
    selected_total = total_scores_df[total_scores_df["asset_id"] == asset_id]
    if selected_total.empty:
        raise ValueError(f"No score found for asset_id: {asset_id}")

    total_row = selected_total.iloc[0]
    selected_modules = module_scores_df[module_scores_df["asset_id"] == asset_id].copy()
    valid_modules = selected_modules.dropna(subset=["module_score"])
    strongest_module = None
    weakest_module = None
    if not valid_modules.empty:
        strongest_row = valid_modules.loc[valid_modules["module_score"].idxmax()]
        weakest_row = valid_modules.loc[valid_modules["module_score"].idxmin()]
        strongest_module = {
            "module": strongest_row["module"],
            "score": _to_float(strongest_row["module_score"]),
        }
        weakest_module = {
            "module": weakest_row["module"],
            "score": _to_float(weakest_row["module_score"]),
        }

    missing_count = int(selected_modules["missing_indicator_count"].sum())
    missing_summary = (
        f"{missing_count} missing indicator(s) were excluded from module averages."
        if missing_count
        else "No missing indicators were excluded from module averages."
    )

    return {
        "total_score": _to_float(total_row["total_score"]),
        "rating_level": total_row["rating_level"],
        "strongest_module": strongest_module,
        "weakest_module": weakest_module,
        "module_scores": selected_modules,
        "missing_indicator_summary": missing_summary,
        "explanation": total_row["explanation"],
    }


def summarize_risk(
    asset_id: str,
    data_dir: str | Path = "data",
    financial_data_source: str = "demo",
) -> dict[str, Any]:
    """Summarize latest risk metrics and sample-relative high-risk categories."""
    context = get_asset_context(asset_id, data_dir, financial_data_source)
    risk_row = context["risk"]
    risk_sample = context["risk_sample"]

    if risk_row is None:
        return {
            "high_relative_risks": [],
            "risk_values": {},
            "risk_summary_text": "Risk metrics are unavailable for this asset.",
        }

    risk_values: dict[str, float | None] = {}
    high_relative_risks: list[str] = []
    for column, label in RISK_COLUMNS.items():
        value = _to_float(risk_row.get(column))
        risk_values[label] = value
        sample_values = pd.to_numeric(risk_sample[column], errors="coerce").dropna()
        if value is not None and not sample_values.empty and value >= sample_values.quantile(0.75):
            high_relative_risks.append(label)

    if high_relative_risks:
        summary = (
            "High sample-relative risk categories include "
            + ", ".join(high_relative_risks)
            + ". Risk interpretation is sample-relative in the MVP."
        )
    else:
        summary = "No risk category is above the sample 75th percentile. Risk interpretation is sample-relative in the MVP."

    return {
        "high_relative_risks": high_relative_risks,
        "risk_values": risk_values,
        "risk_summary_text": summary,
    }


def _validity_summary(data_dir: str | Path = "data") -> dict[str, Any]:
    validity_results = run_model_validity_pipeline(data_dir)
    cronbach = validity_results["cronbach_alpha"]
    ahp = validity_results["ahp_consistency"]
    sensitivity = validity_results["sensitivity_analysis"]
    content_table = validity_results["content_validity_table"]
    return {
        "content_indicator_count": len(content_table),
        "cronbach_status": cronbach.get("status"),
        "cronbach_explanation": cronbach.get("explanation"),
        "ahp_status": ahp.get("status"),
        "ahp_explanation": ahp.get("explanation"),
        "ranking_stability_ratio": sensitivity.get("ranking_stability_ratio"),
        "average_spearman_correlation": sensitivity.get("average_spearman_correlation"),
        "sensitivity_explanation": sensitivity.get("explanation"),
    }


def generate_management_suggestions(
    score_summary: dict[str, Any],
    gatekeeper_summary: dict[str, Any],
    risk_summary: dict[str, Any],
    context: dict[str, Any],
    scenario_result: dict[str, Any] | None = None,
) -> list[str]:
    """Generate deterministic management suggestions from model outputs."""
    suggestions: list[str] = []
    weak_module = (score_summary.get("weakest_module") or {}).get("module", "")
    warning_conditions = set(gatekeeper_summary.get("warning_conditions", []))
    high_risks = set(risk_summary.get("high_relative_risks", []))

    financial = context["financial"]
    operation = context["operation"]
    service = context["service_quality"]
    coverage = None
    if financial is not None:
        coverage = _to_float(financial.get("estimated_affo"))
        distribution = _to_float(financial.get("estimated_distribution"))
        coverage = coverage / distribution if coverage is not None and distribution else None

    if "Tourism Operating Quality" in weak_module or "seasonality risk" in high_risks:
        suggestions.append("Improve off-peak demand through event programming, bundled stays, and channel partnerships.")
    if operation is not None and _to_float(operation.get("secondary_spending_ratio")) is not None:
        suggestions.append("Diversify non-ticket and secondary spending revenue to reduce dependence on core admission or room revenue.")
    if "platform dependency risk" in high_risks:
        suggestions.append("Reduce platform dependency by strengthening direct booking, membership, and owned customer channels.")
    if "climate physical risk" in high_risks or "continuous_operation_warning" in warning_conditions:
        suggestions.append("Strengthen climate-risk monitoring, emergency response planning, insurance review, and operating continuity controls.")
    if "Data Maturity" in weak_module:
        suggestions.append("Improve data disclosure, data quality controls, and digital operation dashboards for repeatable asset monitoring.")
    if "capex_pressure_warning" in warning_conditions:
        suggestions.append("Control maintenance CAPEX pressure through lifecycle planning and transparent reserve policies.")
    if service is not None and (_to_float(service.get("ota_score")) or 5) < 4.4:
        suggestions.append("Enhance service quality dimensions reflected in online reviews, especially responsiveness and reliability.")
    if coverage is not None and coverage < 1.1:
        suggestions.append("Strengthen cash-flow coverage of distributions through cost discipline and recurring revenue quality.")
    if scenario_result and scenario_result.get("severity") in {"High Impact", "Severe Impact"}:
        suggestions.append("Prepare downside response plans for stress scenarios that pressure AFFO proxy and distribution coverage.")

    if not suggestions:
        suggestions.append("Maintain current monitoring discipline and continue improving documentation of source data and assumptions.")

    return suggestions[:5]


def _markdown_table_from_module_scores(module_scores: pd.DataFrame) -> str:
    if module_scores.empty:
        return "Module scores are unavailable."
    rows = ["| Module | Score | Valid Indicators | Missing Indicators |", "| --- | ---: | ---: | ---: |"]
    for row in module_scores.itertuples(index=False):
        rows.append(
            f"| {row.module} | {format_number(row.module_score)} | "
            f"{row.valid_indicator_count} | {row.missing_indicator_count} |"
        )
    return "\n".join(rows)


def _scenario_section(scenario_result: dict[str, Any]) -> str:
    parameters = scenario_result["scenario_parameters"]
    parameter_lines = "\n".join(
        f"- `{key}`: {format_percentage(value) if key != 'ota_score_decline' else format_number(value)}"
        for key, value in parameters.items()
        if value
    )
    if not parameter_lines:
        parameter_lines = "- No active shock parameters."

    impact = scenario_result["impact_metrics"]
    base = scenario_result["base_metrics"]
    simulated = scenario_result["simulated_metrics"]

    return f"""## Scenario Simulation Result

Scenario outputs are simulated stress-test estimates for portfolio demonstration and are not forecasts.

### Scenario Parameters

{parameter_lines}

### Impact Summary

- Score impact: {format_number(scenario_result["base_score"], decimals=1)} to {format_number(scenario_result["simulated_score"], decimals=1)} ({format_number(scenario_result["score_change"], decimals=1)} points).
- Cash flow impact: operating cash flow change of {format_number(impact.get("operating_cash_flow_change"))}.
- AFFO impact: {format_number(base.get("estimated_affo"))} to {format_number(simulated.get("affo_after"))}.
- Distribution coverage impact: {format_number(base.get("distribution_coverage"))} to {format_number(simulated.get("distribution_coverage_after"))}.
- Severity: {scenario_result["severity"]}.

{scenario_result["explanation"]}
"""


def generate_asset_report(
    asset_id: str,
    data_dir: str | Path = "data",
    weight_mode: str = "default_expert_weight",
    scenario_result: dict[str, Any] | None = None,
    output_format: str = "markdown",
    financial_data_source: str = "demo",
) -> str:
    """Generate a deterministic Markdown report for one asset."""
    if output_format != "markdown":
        raise ValueError("Only markdown output_format is currently supported.")

    context = get_asset_context(asset_id, data_dir, financial_data_source)
    asset = context["asset"]
    financial = context["financial"]
    operation = context["operation"]
    service = context["service_quality"]
    risk = context["risk"]
    gatekeeper = summarize_gatekeeper(asset_id, data_dir, financial_data_source)
    score = summarize_score(asset_id, data_dir, weight_mode, financial_data_source)
    risk_summary = summarize_risk(asset_id, data_dir, financial_data_source)
    validity = _validity_summary(data_dir)
    suggestions = generate_management_suggestions(score, gatekeeper, risk_summary, context, scenario_result)

    conclusion = (
        f"{asset['asset_name']} is classified as {score['rating_level']} with a "
        f"{gatekeeper['overall_status']} Regulatory Gatekeeper status in this portfolio prototype."
    )
    if scenario_result:
        conclusion += f" Under the supplied scenario, severity is {scenario_result['severity']}."

    strongest = score["strongest_module"] or {"module": "Data unavailable", "score": None}
    weakest = score["weakest_module"] or {"module": "Data unavailable", "score": None}
    coverage = None
    if financial is not None:
        coverage = _to_float(financial.get("estimated_affo"))
        distribution = _to_float(financial.get("estimated_distribution"))
        coverage = coverage / distribution if coverage is not None and distribution else None

    scenario_text = _scenario_section(scenario_result) if scenario_result else ""
    sensitivity_ratio = validity["ranking_stability_ratio"]
    spearman = validity["average_spearman_correlation"]

    report = f"""# Tourism REIT Asset Evaluator Report: {asset['asset_name']}

## Executive Summary

- Asset name: {asset['asset_name']}
- Asset type: {asset['asset_type']}
- Gatekeeper overall status: {gatekeeper['overall_status']}
- REITs suitability score: {format_number(score['total_score'], decimals=1)}
- Rating level: {score['rating_level']}
- Scenario severity: {scenario_result['severity'] if scenario_result else 'No scenario provided'}
- Conclusion: {conclusion}

## Asset Profile

- Location: {asset['location']}
- Description: {asset['description']}
- Asset type: {asset['asset_type']}
- Data type: {asset['data_type']}
- Source note: {asset['source_note']}

## Regulatory Gatekeeper Review

- Overall status: {gatekeeper['overall_status']}
- Passed conditions: {_format_list(gatekeeper['passed_conditions'])}
- Failed conditions: {_format_list(gatekeeper['failed_conditions'])}
- Warning conditions: {_format_list(gatekeeper['warning_conditions'])}

{gatekeeper['summary_text']}

This review is a regulatory-style portfolio prototype screen. It is not an official regulatory review or approval conclusion.

## REITs Suitability Score

- Total score: {format_number(score['total_score'], decimals=1)}
- Rating level: {score['rating_level']}
- Strongest module: {strongest['module']} ({format_number(strongest['score'], decimals=1)})
- Weakest module: {weakest['module']} ({format_number(weakest['score'], decimals=1)})
- Missing indicator note: {score['missing_indicator_summary']}

{_markdown_table_from_module_scores(score['module_scores'])}

The score is a portfolio demonstration output and is not an official rating.

## Cash Flow and Distribution Capacity

- Base revenue: {format_number(_safe_value(financial, 'revenue'))}
- NOI: {format_number(_safe_value(financial, 'noi'))}
- Operating cash flow: {format_number(_safe_value(financial, 'operating_cash_flow'))}
- AFFO proxy: {format_number(_safe_value(financial, 'estimated_affo'))}
- Estimated distribution: {format_number(_safe_value(financial, 'estimated_distribution'))}
- Distribution coverage: {format_number(coverage)}

Field source note: {FIELD_SOURCE_DISCLOSURE}
"""

    if scenario_result:
        report += f"""
### Scenario Cash Flow Comparison

- Base vs simulated NOI: {format_number(scenario_result['base_metrics'].get('noi'))} to {format_number(scenario_result['simulated_metrics'].get('noi_after'))}
- Base vs simulated AFFO proxy: {format_number(scenario_result['base_metrics'].get('estimated_affo'))} to {format_number(scenario_result['simulated_metrics'].get('affo_after'))}
- Base vs simulated distribution coverage: {format_number(scenario_result['base_metrics'].get('distribution_coverage'))} to {format_number(scenario_result['simulated_metrics'].get('distribution_coverage_after'))}
"""

    report += f"""
## Tourism Operation and Service Quality

- Visitor volume: {format_number(_safe_value(operation, 'visitor_volume'), decimals=0)}
- Occupancy rate: {format_percentage(_safe_value(operation, 'occupancy_rate'))}
- ADR: {format_number(_safe_value(operation, 'adr'))}
- RevPAR: {format_number(_safe_value(operation, 'revpar'))}
- OTA score: {format_number(_safe_value(service, 'ota_score'))}
- Review count: {format_number(_safe_value(service, 'review_count'), decimals=0)}
- Secondary spending ratio: {format_percentage(_safe_value(operation, 'secondary_spending_ratio'))}

Missing fields are shown as `Data unavailable` and should not be inferred from demo data.

## Risk Warning

{risk_summary['risk_summary_text']}

- Seasonality risk: {format_number(_safe_value(risk, 'seasonality_risk'))}
- Policy risk: {format_number(_safe_value(risk, 'policy_risk'))}
- Climate physical risk: {format_number(_safe_value(risk, 'climate_physical_risk'))}
- Financial pressure risk: {format_number(_safe_value(risk, 'financial_pressure_risk'))}
- Platform dependency risk: {format_number(_safe_value(risk, 'platform_dependency_risk'))}

Risk interpretation is sample-relative in the MVP and does not represent official thresholds.

{scenario_text}

## Model Validity and Limitations

- Content validity: {validity['content_indicator_count']} indicators are mapped to reference frameworks and validation notes.
- Cronbach's Alpha applicability: {validity['cronbach_explanation']}
- AHP consistency: {validity['ahp_explanation']}
- Sensitivity analysis: {validity['sensitivity_explanation']}
- Ranking stability ratio: {format_percentage(sensitivity_ratio) if sensitivity_ratio is not None else 'Data unavailable'}
- Average Spearman correlation: {format_number(spearman, decimals=3)}
- Demo data limitation: demo data may include simulated or mixed values.
- Small-sample limitation: the current sample is too small for broad statistical inference.

## Management Suggestions

{chr(10).join(f'- {suggestion}' for suggestion in suggestions)}

## Disclaimer

This report is generated for portfolio demonstration and asset management support.
{FIELD_SOURCE_DISCLOSURE}
It is not investment advice.
It is not a credit rating.
It is not a valuation opinion.
It is not an official regulatory conclusion.
Demo data may include simulated or mixed values.
"""

    return report


def save_report(report_text: str, output_path: str | Path) -> Path:
    """Save a Markdown or text report."""
    path = Path(output_path)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    if path.suffix.lower() not in {".md", ".txt"}:
        raise ValueError("output_path must end with .md or .txt")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report_text, encoding="utf-8")
    return path


def run_demo_report(data_dir: str | Path = "data") -> list[Path]:
    """Generate one demo Markdown report for each asset."""
    scoring_df, _tables = load_scoring_data(data_dir)
    asset_ids = scoring_df["asset_id"].dropna().astype(str).tolist()
    saved_paths: list[Path] = []

    for index, asset_id in enumerate(asset_ids, start=1):
        report_text = generate_asset_report(asset_id, data_dir=data_dir)
        saved_paths.append(save_report(report_text, PROJECT_ROOT / "reports" / f"report_A{index:03d}.md"))

    return saved_paths


def _print_cli_output() -> None:
    saved_paths = run_demo_report()
    print("Saved report paths:")
    for path in saved_paths:
        print(f"- {path}")

    if saved_paths:
        preview = saved_paths[0].read_text(encoding="utf-8").splitlines()[:35]
        print("\nPreview:")
        print("\n".join(preview))


if __name__ == "__main__":
    _print_cli_output()
